### ISSUE TITLE
Uso de elementos do DOM diretamente no VUE

### ISSUE THREAD

**Issue by gamichalski** [geanfarias/quiz-buzzfeed#2]
Em 99,9% dos casos, não é muito interessante fazer a manipulação do dom diretamente sem utilizar os recursos do VUE.
Todas a manipulações que foram feitas dentro desse arquivo podem ser feitas utilizando os recursos do Vue. Como por exemplo:

Aqui, você fazer utilizando class binding:
https://github.com/geanfarias/quiz-buzzfeed/blob/bb1c334eff8ef9a464fd7e534fc722447cd64248/src/components/questions.vue#L77

**Comment by geanfarias** [comment]
corrigido.
