### ISSUE TITLE
Operador ternario

### ISSUE THREAD

**Issue by gamichalski** [geanfarias/quiz-buzzfeed#3]
Você pode nesse caso usar um operador ternário reduzindo bastante a quantidades de linhas. Ficando dessa forma:
```this.$data.correctAnswers != 0 ? "Não foi dessa vez. Tente novamente." : `Você acertou ${this.$data.correctAnswers} de ${this.$data.valores.length}, Parabéns!`; ```

https://github.com/geanfarias/quiz-buzzfeed/blob/bb1c334eff8ef9a464fd7e534fc722447cd64248/src/components/questions.vue#L108

**Comment by geanfarias** [comment]
implementado de outra forma, mas obrigado pela observação.
